general:
  title: ubuntu-22.04-vncTest
  category: Experimental
  image: Ubuntu-22.04-LTS-20250514-PDCCloud.1
  weblink: http://{{IP}}:8080
packages:
- wget
- git
- bash
- gcc
- gfortran
- g++
- make
password: REQUIRED
