general:
  title: VeloxChem Dev (KCSCLab)
  category: Chemistry
  base_image: Rocky-9-LVM-9.8-20260525.0.KCSCCloud-Lab.0
  weblink: https://{{IP}}/
users:
- username: REQUIRED
  password: REQUIRED
branches:
- master
