general:
  title: Bioinformatics Course
  category: Experimental
  base_image: Ubuntu-24.04-LTS-20250313-PDCCloud.1
packages:
- wget
- git
- bash
- gcc
- gfortran
- g++
- make
- nano
- curl
- python3
- python3-venv
- openjdk-17-jre-headless
- rclone
- jq
- emboss
- 7zip
- python3-biopython
- pymol
- mmseqs2
- clustalw
- python3-pip
pip:
- seaborn
- scikit-learn
- pandas
- numpy
snap:
- emacs --classic
users:
- arnee
