general:
  title: Ubuntu 24.04 LTS with OpenMPI and Rscript
  category: Experimental
  base_image: Ubuntu-24.04-LTS-20250313-PDCCloud.1
users:
- username: REQUIRED
  password: REQUIRED
packages:
- bash
- make
- micro
Rpackages:
- pbdMPI
- ks
- MASS
- VineCopula
- Ryacas
- remotes
- devtools
- icpm-kth/SBtabVFGEN
- icpm-kth/rgsl
- icpm-kth/uqsa
