general:
  title: GROMACS
  category: Chemistry
  image: Ubuntu-24.04-LTS-20260801-KCSCCloud.0
version: latest
packages:
- wget
- git
- bash
- gcc
- gfortran
- g++
- make
- nano
- cmake
- libfftw3-dev
- libxml2-dev
- libboost-all-dev
- libopenmpi-dev
- openmpi-bin
