general:
  title: VeloxChem Dev (PDCLab v0.1.4)
  Category: XtraOld
  image: Rocky-9-LVM-9.7-20251123.2.KCSCCloud-Lab.1
  weblink: https://{{IP}}/
users:
- username: REQUIRED
  password: REQUIRED
branches:
- master
